/** Static select options for profile edit forms (model / configuration). */

export const DISTRICT_OPTIONS = [
    'Ancón',
    'Ate',
    'Barranco',
    'Breña',
    'Carabayllo',
    'Cercado de Lima',
    'Chaclacayo',
    'Chorrillos',
    'Cieneguilla',
    'Comas',
    'El Agustino',
    'Independencia',
    'Jesús María',
    'La Molina',
    'La Victoria',
    'Lince',
    'Los Olivos',
    'Lurigancho (Chosica)',
    'Lurín',
    'Magdalena del Mar',
    'Miraflores',
    'Pachacámac',
    'Pucusana',
    'Pueblo Libre',
    'Puente Piedra',
    'Punta Hermosa',
    'Punta Negra',
    'Rímac',
    'San Bartolo',
    'San Borja',
    'San Isidro',
    'San Juan de Lurigancho',
    'San Juan de Miraflores',
    'San Luis',
    'San Martín de Porres',
    'San Miguel',
    'Santa Anita',
    'Santa María del Mar',
    'Santa Rosa',
    'Santiago de Surco',
    'Surquillo',
    'Villa El Salvador',
    'Villa María del Triunfo',
] as const;

export const INDUSTRY_OPTIONS = [
    'Tecnología',
    'Finanzas',
    'Salud',
    'Educación',
    'Retail',
    'Manufactura',
    'Servicios',
    'Construcción',
    'Comercio',
    'Transporte y logística',
    'Gastronomía y turismo',
    'Otro',
] as const;

export const COMPANY_SIZE_OPTIONS = [
    { value: '1-10', label: '1 – 10' },
    { value: '11-50', label: '11 – 50' },
    { value: '51-200', label: '51 – 200' },
    { value: '201-500', label: '201 – 500' },
    { value: '501+', label: '501+' },
] as const;

export const PROFILE_BIO_MAX_LENGTH = 500;
